### PR TITLE
Feature: EcoPortal share social

### PR DESCRIPTION
**Pull request by syphax-bouazzouni**
See details on https://github.com/lifewatch-eric/ecoportal_web_ui/pull/10

### CODE REVIEW

**Comment by syphax-bouazzouni** [comment]
@jonquet  do you want this in Agroportal?

**Comment by jonquet** [comment]
Yes why not...with a more explicit social post message, this coule be relevant. And I am very much in favor on getitng the same things all. 
We need to see with @hibadjebabria169 were it would fit in the page. We need to discuss with @Bilelkihal a potential better integration everywhere in the portal => when someone is on a page, the post  will change...

**Comment by syphax-bouazzouni** [comment]
Can you propose a template for this @SirineMhedhbi ?

**Comment by syphax-bouazzouni** [comment]
Close as not wanted

**Comment by jonquet** [comment]
Just to be sure: is this in our code and not activated by a config parameter?
I mean, any features developed in every portal should be as much as possible in every OntoPortal code to avoid differences when merging branches.

**Comment by syphax-bouazzouni** [comment]
Not in our code, as the code is not compatible with our current version of the code.
To implement it in our version, they (or we) will need to update it to use the current version.

**Comment by jonquet** [comment]
So not sure we should close this and it shall wait the next merge of the Eco/AgroPortal UIs where we will need to integrate this in our master branch before redistributing it to EcoPortal.

**Pull request closed without merging**
