### PR TITLE
Fix: Prevent display home portal tooltip if we get a non complete response

### PR DESCRIPTION
**Pull request by Bilelkihal**
Fix: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/835

Before:
image

After:
image

### CODE REVIEW

**Review by Bilelkihal — COMMENTED** [review]
✅

**Review by syphax-bouazzouni — CHANGES_REQUESTED** [review]
Here we need to show anything the API does return even if it is only the ontologies count, we will not have always the full attributes so it need to adapt, and not hide everything.

**Comment by Bilelkihal** [comment]
> Here we need to show anything the API does return even if it is only the ontologies count, we will not have always the full attributes so it need to adapt, and not hide everything.

@syphax-bouazzouni 
Done
image

**Comment by Bilelkihal** [comment]
@syphax-bouazzouni ping

**Review by syphax-bouazzouni — APPROVED** [review]

**Pull request merged**
