### PR TITLE
Fix: propertyid param auto added to summary page URL

### PR DESCRIPTION
**Pull request by Bilelkihal**
### Related issue
https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/715

### Description of the solution
I disabled auto clicking on the first element of the tree (still will be highlighted) and made by default the right section initialized with the details of this first element.
So we get the exact behavior we want (like for the concepts tab)

### CODE REVIEW

**Review by syphax-bouazzouni — CHANGES_REQUESTED** [review]
Add in the description what was the issue, and how did you fix it.

**Review by Bilelkihal — COMMENTED** [review]
@syphax-bouazzouni 
Done ✅

**Comment by Bilelkihal** [comment]
> why you not disabling auto loading for the all the tabs, and why does this occur only for the properties tab, not the classes for example which also auto-select the first concept

Why not disabling it for all tabs?
- I see it better to keep loading them in the background since this doesn't affect the initial loading of the page.

Why this occur only in the properties tab on not the other onces?
- I don't know

**Comment by Bilelkihal** [comment]
@syphax-bouazzouni Done, and deployed to stage, you can test it with obo-foundry ontologies like AGRO, TO to test properties and instances.

For the solution I did:
I disabled auto clicking on the first element of the tree (still will be highlighted) and made by default the right section initialized with the details of this first element.
So we get the exact behavior we want (like for the concepts tab)

**Review by syphax-bouazzouni — CHANGES_REQUESTED** [review]

**Review by Bilelkihal — COMMENTED** [review]
Done ✅

**Review by syphax-bouazzouni — APPROVED** [review]

**Pull request merged**
