### PR TITLE
Fix: Wrong concepts chips links

### PR DESCRIPTION
**Pull request by Bilelkihal**
Related issue:
https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/528

The problem was traced back to an issue in the Stimulus base project, as detailed in [stimulus issue #618](https://github.com/hotwired/stimulus/issues/618)

and the only proposed solution is by set a timout of 0s in the connect method, and it worked.

### CODE REVIEW

**Review by Bilelkihal — COMMENTED** [review]
✅

**Review by syphax-bouazzouni — CHANGES_REQUESTED** [review]
Give more details about the issue in the description, so that I can understand the original problem. 

And anyway, here the requirement is to remove this label_ajax_controller code, and replace it with a turbo frame as you did, with the mappings counts.

**Comment by Bilelkihal** [comment]
@syphax-bouazzouni 
Well when we refresh the page everything works well, but once u select a term in the tree view (we refresh only that a the turbo frame of the concept details) then we get an error in the JS saying: 

> The provided outlet element is missing the outlet controller "label-ajax" for "labels-ajax-container"

and this means that this element is missing the connect method or something like this, and the solution I found in the discussion of this issue: https://github.com/hotwired/stimulus/issues/618
is to add a setimout of 0s in the connect method

**Review by syphax-bouazzouni — CHANGES_REQUESTED** [review]
here the requirement is to remove this `label_ajax_controller` code, and replace it with a turbo frame as you did, with the mappings counts.

**Comment by Bilelkihal** [comment]
> here the requirement is to remove this `label_ajax_controller` code, and replace it with a turbo frame as you did, with the mappings counts.

This will be a big project, I'll do it last

**Comment by Bilelkihal** [comment]
@syphax-bouazzouni By now you can merge this PR, I'll do the refactoring of the code in a separate PR in the future

**Comment by syphax-bouazzouni** [comment]
> @syphax-bouazzouni By now you can merge this PR, I'll do the refactoring of the code in a separate PR in the future

`in the future`, means generally never. But OK, can you open another issue so we don't forget to do it?

**Pull request merged**
