### PR TITLE
Fix: Reject the current ontology from appearing in the ontologies selector in editing the submission's relations

### PR DESCRIPTION
**Pull request by Bilelkihal**
Related issue: https://github.com/agroportal/project-management/issues/557#event-12970003146

Screenshot:
Capture d’écran 2024-05-29 à 17 09 25

### CODE REVIEW

**Review by syphax-bouazzouni — APPROVED** [review]

**Review by syphax-bouazzouni — CHANGES_REQUESTED** [review]
this will not work in admin page, using the metadata curator. 

because `@ontology` does not exist

**Comment by Bilelkihal** [comment]
> this will not work in admin page, using the metadata curator.
> 
> because `@ontology` does not exist

@syphax-bouazzouni 
Capture d’écran 2024-05-30 à 16 57 21

No it's  working, and @ontology is defined when we call this element.
Capture d’écran 2024-05-30 à 16 58 47

**Comment by syphax-bouazzouni** [comment]
@Bilelkihal ; try multiple ontologies maybe? 

anyway, try to add it as an argument, like this future developers will know that it use an external `@ontoology`. Like this
```ruby
def generate_ontology_select_input(name, label, selected, multiple, reject_ontology = @ontology)
```

**Comment by Bilelkihal** [comment]
Done,
And it worked for multiple also, because the @ontology for every selected is related to the turbo frame the selected is inside it.
Capture d’écran 2024-05-30 à 22 48 18

**Pull request merged**
