### PR TITLE
Fix: losing context when changing language in concepts page

### PR DESCRIPTION
**Pull request by Bilelkihal**
### Related issues:
https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/557
https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/617
https://github.com/agroportal/project-management/issues/518

### Description
To see the problem:
1- Pick concept 'A' from the tree view.
2- Change language to French for example.
3- Change language to All languages.
4- Choose concept 'B'.
5- Go back to French.
Now, instead of showing concept 'B' in French, it goes back to showing 'A'.

### Technical Cause
Though the exact issue remains somewhat elusive, here's how it unfolds: when the language is changed, the select component triggers an event called 'lang_changed'. This event is intercepted to update the URL via the history stimulus controller, and refresh the content frame via the turbo frame controller
`action: "lang_changed->history#updateURL lang_changed->turbo-frame#updateFrame"`

In attempting to trace the execution flow leading to the anomaly, I encountered an unusual occurrence within the history stimulus controller. While debugging the JavaScript line by line, I observed an abrupt change in window.location.search to an incorrect concept.

### Justification of the Technical Choice
I opted to refresh the page each time the language changes, but using Turbo to do it without reloading the whole browser.
Benifits:
- Issue resolved
- Performance remains the same because we were refreshing the bottom part of the page anyway, while keeping the header.
- The code for changing languages is now simpler and in one place.

### CODE REVIEW

**Review by Bilelkihal — COMMENTED** [review]
✅

**Review by syphax-bouazzouni — APPROVED** [review]
the fix seems fine by me, simplicity is always better.
But can you just add a video, I want to see if refresh page doesn't degrade the UX of refreshing only content part.

**Comment by syphax-bouazzouni** [comment]
Great PR description, btw.

**Review by syphax-bouazzouni — CHANGES_REQUESTED** [review]
After testing it, it did not work 

https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/9600fbe5-3c76-4950-beb4-8dfca22be235

**Comment by Bilelkihal** [comment]
> After testing it, it did not work
> 
>  Enregistrement.de.l.ecran.2024-06-03.a.14.31.33.mov

It's weird that u r in the Animal husbandry and breeding class without having it in the params of your browser URL.
anyway, this is then a whole different issue

**Comment by Bilelkihal** [comment]
@syphax-bouazzouni how did you arrive to this class?

**Comment by syphax-bouazzouni** [comment]
> > After testing it, it did not work
> > Enregistrement.de.l.ecran.2024-06-03.a.14.31.33.mov
> 
> It's weird that u r in the Animal husbandry and breeding class without having it in the params of your browser URL. anyway, this is then a whole different issue
To reproduce:
* went to INREATHES concepts tabs
* Open one the tree of the concept "02. AGRI....."
* Clicked on the "Animal husbandry...", 
* Then tried to change the language.
lost the context

**Comment by Bilelkihal** [comment]
Yes, you are right, I broke the original behavior when I tried to clean the old code of the language selector, now it's working:

https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/550b93cd-8dbc-408b-aadf-8a4ed9df4300

**Comment by Bilelkihal** [comment]
> Yes, you are right, I broke the original behavior when I tried to clean the old code of the language selector, now it's working:
> 
>  Enregistrement.de.l.ecran.2024-06-03.a.16.45.47.mov

I also tested the case:
1- Pick concept 'A' from the tree view.
2- Change language to French for example.
3- Change language to All languages.
4- Choose concept 'B'.
5- Go back to French.

and it's working correclty

**Comment by syphax-bouazzouni** [comment]
> Yes, you are right, I broke the original behavior when I tried to clean the old code of the language selector, now it's working:
> 
>  Enregistrement.de.l.ecran.2024-06-03.a.16.45.47.mov

From this video, I  see two other issues:
* The UX is less good, the progress is full, but you wait 2-5s seconds after to see the content, without anything telling you that it is loading.
* The split component is rendered each time you refresh, I think
image

**Comment by Bilelkihal** [comment]
> > Yes, you are right, I broke the original behavior when I tried to clean the old code of the language selector, now it's working:
> > Enregistrement.de.l.ecran.2024-06-03.a.16.45.47.mov
> 
> From this video, I see two other issues:
> 
> * The UX is less good, the progress is full, but you wait 2-5s seconds after to see the content, without anything telling you that it is loading.
> * The split component is rendered each time you refresh, I think
>   image

Thanks for ur remark, then the only solution is to refrech the whole page:

https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/4828e5da-8f34-4d16-9de4-e7a1121a5aea

PS. my dev environment is slower in general it's not related to this

**Comment by syphax-bouazzouni** [comment]
Nah refreshing all the pages, is old school.

The old way of refreshing only the frame was better, even if it is more complex. You just need to know why we did lose the context and fix only that.

**Comment by syphax-bouazzouni** [comment]
@Bilelkihal postpone this, will go back to it in the future.  
You can deploy this version (branch) to TestPortal, if you want to see it in production, maybe it is good enough.

**Review by syphax-bouazzouni — APPROVED** [review]
updated the code to fix the issue of not saving the good current URL

**Comment by Bilelkihal** [comment]
Not working for the initial use case issue:
1- Pick concept 'A' from the tree view.
2- Change language to French for example.
3- Change language to All languages.
4- Choose concept 'B'.
5- Go back to French.
Now, instead of showing concept 'B' in French, it goes back to showing 'A'.

**Review by Bilelkihal — COMMENTED** [review]
Working ✅

**Comment by user34ngrau** [comment]
Q&A session - 5th September (Anne sophie & Nina)
Template used: Number - [Title of the issue] : [Description of the issue] followed by an example : text and/ or screenshot and/or recording”

1-[Langue des catégories du filtre] : [Quand on met la langue du site en francais les sous categories du filtre "Langues naturelles", "niveaux de formalité" restent en anglais]
image

2- [Selection d'ontologies multilangues] : [Pas de possibilité de faire un regroupement/intersection d'ontologies qui comprennent plusieurs langues] 
Ex: je souhaite voir des ontologies qui sont en francais ET en anglais, or je n'obtiens que les ontologies qui ont soit une des langues ou l'autre
https://github.com/user-attachments/assets/da551229-289a-4996-847f-4ff1554abc88

3-[Langue de définition des classes] : [La definition d'une classe est décrite en anglais alors que la langue du contenu est le francais]
Ex: AHOL ontology
image

4-[Langue de synonymes des classes] : [Pas de synonmye francais pour certaines classes]
Ex: GAO ontology
image

5-[Orthographe de synonymes des classes] : [Pas d'harmonisation de notation des synonymes]
Ex: GAO ontology, certains termes ont des majuscules et d'autres en minuscules
image

6-[Labélisation nom préféré pour synonyme des classes] : [Pas label de "nom préféré" pour des synonymes]
Ex: GAO ontology, pas d'indication du "nom préféré" pour le synonyme "shoot apex"
image

7-[Classement des noms préférés des classes] : [En fonction des classes selectionnées, la langue préférée qui apparait en premier varie]
Ex: GAO ontology, pour la classe "reproductive organes", le nom préféré est en anglais alors que pour "vegetative organs" cest le terme francais qui apparait en premier
https://github.com/user-attachments/assets/d2366ac8-4d42-44ad-bc06-0182f7143743

to be continued

**Pull request merged**
