### PR TITLE
Feature: Update browse page design

### PR DESCRIPTION
**Pull request by syphax-bouazzouni**
### Context
https://github.com/agroportal/project-management/issues/313
### TODO

- [x] Update the new UI
- [x] Remove angular and semantics UI
- [x] Make the UI backend do the filters
- [x] Use Hotwire to make a single page 
- [x] Do the pagination in the API (see https://github.com/ontoportal-lirmm/ontologies_api/pull/34 and https://github.com/ontoportal-lirmm/ontologies_api/pull/36)

### Changes

- Update browse page design with the new design on figma (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/f5b8a651710a86549c98a22ee65ded726e3f0afa)
- Fix the problems in the design of the browse page and make it responsive (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/ceeedb1b783d083bbc4987c060ce83c3d0f8fe14)
- Update the design of the switch component (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/e10b7e7f397ccfbd4d8acd93bc40f29936ff41da)
- Add the checked property to the chips component (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/c57eb9faf3dcc71b0b60d3c3da72cc439c1616e1)
- Add the checked filters count in the browse page (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/75705a63541f29d051e3d26193ac9a1ba8315f65)

- Remove the angular from the browse page(https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/c5c98fa888a5aab9075483447087c3988c049520)

- In the browse page, limit the ontology description to 3 lines and add a b…](https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/b4a201fb8c5fbcb121748f51f95b22e5c890a319)

- Add text truncate stimulus controller (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/482f8f1eda776d33fbebce215b5b40c092f8b21a)

- Replace in the browser descriptions js with a controller to show more (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/d48110854cb64a41c6e5425fc03d7aae41f60c03)

- Add time ago stimulus controller to show dates in a human-readable way (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/ac4e2e7c94d7f232fd8486855652a7eb67f5370e)

- Add ontology contacts and format to the ontology card (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/8605597a55272e217da70d631f69e61d85006008)

- Remove old angular files (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/a9b54b9df2a1ed4f938584125d187dd2363176ba)

- Add ontology browser page and empty state image (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/16b125d20c417fc3e10c33760e315371aa56073b)

- Refactor use history mixin (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/30fbf0c77deef25110ccf66c3988849a01eba235)

- Add count slot to the chip's components (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/7ad74f1b340c178680052ea9aa6b8bde9f4918c2)

- Add a small version of the loader component](https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/501d5616f1db7803be4e86504e891c7ae968f0ac)

- Add the count slots to the chips in the browse page (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/4408de7cc5ce130f3a66590cdcd3a71b8a0cbed6)

- Use turbo streams to update ontologies result and the filter counts (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/e7d3f5e5b916dad12ac36d3dbd80b09267a52a81)

- Add ontology browse private icon (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/b221479de075ff930bc3abcabafaf20caccdbabf)

- Add admin-color theme variable (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/6609f8a169e8e362171330c293da2d46020f3dd1)

- Add title tooltip for the browser filters chips](https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/1eca78dab43925644f2898ea1c2d03d2a57a1459)

- Migrate the fair score js code to stimulus to make it work with turbo (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/724ba80dcde3f28b8a0a770a59d26450520ee0e4)

### Demo

https://user-images.githubusercontent.com/29259906/235860902-507b1abd-8f12-4c3c-834a-e720565e1503.mov

### CODE REVIEW

**Comment by syphax-bouazzouni** [comment]
@Bilelkihal update the commits messages and respond to me here with the state of advancement and what stays to do. 

We will try to merge this, in the late afternoon.

**Comment by Bilelkihal** [comment]
Update commit messages ✅
**What stays to do:**
- Missing status (admin filter) is not working correctly (we need to do a meet to discuss it soon)
- Limit the ontology description text length to 3-4 lines and add a button "show more" to see the entire text.
- Add the empty illustration when no ontology is found by our search & filtering.

**Comment by syphax-bouazzouni** [comment]
Okey I will try to add the Missing status filter.

For the empty state, I can do it if you give me the html/css template

**Comment by Bilelkihal** [comment]
Limit the ontology description text length to 3 lines and add a button "show more" to see the entire text. ✅

**Comment by syphax-bouazzouni** [comment]
added empty state (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/217/commits/a626c79963ebe2c2dd8131234cd3a261b958196d) done 
image

**Comment by syphax-bouazzouni** [comment]
updated the UI slightly to add ontology format and contact
image

@Bilelkihal what do you think of it?

**Comment by Bilelkihal** [comment]
Perfect, just for the format, it looks weird, it's better to move it to the top (beside the title) or give it the same style as "Uploaded ..."

**Comment by Bilelkihal** [comment]
### For the skelton animation,
**HTML:**

```
<div class="browse-ontology-container">
  <div class="browse-sket">
      <div class="browse-sket-column-one">
          <div class="one"></div>
          <div class="two"></div>
          <div class="three"></div>
          <div class="four"></div>
      </div>
      <div class="browse-sket-column-two">
          <div class="one"></div>
          <div class="two"></div>
          
      </div>
      <div class="browse-sket-column-three">
          <div class="one"></div>
          <div class="two"></div>
      </div>
  </div>
</div>
```

**CSS:**

```
.browse-sket{
    display: flex;
}
.browse-sket-column-one{
    margin-right: 37px;
}
.browse-sket-column-one .one{
    width: 525px;
    height: 50px;
    background: linear-gradient(-90deg, #EEE, #F5F5F5, #EEE);
    border-radius: 5px;
    margin-bottom: 15px;
    background-size: 400% 400%;
    animation: skeleton 3s ease-in-out infinite;
}
.browse-sket-column-one .two{
    width: 525px;
    height: 44px;
    background: linear-gradient(-90deg, #EEE, #F5F5F5, #EEE);
    border-radius: 5px;
    margin-bottom: 15px;
    background-size: 400% 400%;
    animation: skeleton 3s ease-in-out infinite;
}
.browse-sket-column-one .three{
    width: 525px;
    height: 18px;
    background: linear-gradient(-90deg, #EEE, #F5F5F5, #EEE);
    border-radius: 5px;
    margin-bottom: 15px;
    background-size: 400% 400%;
    animation: skeleton 3s ease-in-out infinite;
}
.browse-sket-column-one .four{
    width: 160px;
    height: 36px;
    background: linear-gradient(-90deg, #EEE, #F5F5F5, #EEE);
    border-radius: 5px;
    background-size: 400% 400%;
    animation: skeleton 3s ease-in-out infinite;
}
.browse-sket-column-two{
    margin-right:15px;
}
.browse-sket-column-two .one{
    width: 113px;
    height: 78px;
    background: linear-gradient(-90deg, #EEE, #F5F5F5, #EEE);
    border-radius: 5px;
    margin-bottom: 15px;
    background-size: 400% 400%;
    animation: skeleton 3s ease-in-out infinite;
}
.browse-sket-column-two .two{
    width: 113px;
    height: 78px;
    background: linear-gradient(-90deg, #EEE, #F5F5F5, #EEE);
    border-radius: 5px;
    margin-bottom: 15px;
    background-size: 400% 400%;
    animation: skeleton 3s ease-in-out infinite;
}
.browse-sket-column-three .one{
    width: 113px;
    height: 78px;
    background: linear-gradient(-90deg, #EEE, #F5F5F5, #EEE);
    border-radius: 5px;
    margin-bottom: 15px;
    background-size: 400% 400%;
    animation: skeleton 3s ease-in-out infinite;
}
.browse-sket-column-three .two{
    width: 113px;
    height: 78px;
    background: linear-gradient(-90deg, #EEE, #F5F5F5, #EEE);
    border-radius: 5px;
    margin-bottom: 15px;
    background-size: 400% 400%;
    animation: skeleton 3s ease-in-out infinite;
}

@keyframes skeleton {
    0% {
        background-position: 0 0;
      }
      100% {
        background-position: 400% 0;
        
      }

    
  }
```

**Screenshot:**


https://user-images.githubusercontent.com/61744974/234830260-275d387b-81f7-4661-bb68-f5efa3653662.mp4

**Comment by syphax-bouazzouni** [comment]
@jonquet and @Bilelkihal , please test it in https://testportal.lirmm.fr/ontologies and give me your feedbacks here

**Comment by syphax-bouazzouni** [comment]
Recently found issues:
- Is the search working well?
    - Add acronym and description
    - Private is shown when searched even if  shows_private is disabled
    - When we search for a view it shows even if shows_views is not enabled
    - Search for view with a category does not work

- When we click on the card a `content missing` is shown, fix the links in the cards by adding `turbo-frame-target=”_top”`
- Filter of private ontology is not working

**Comment by syphax-bouazzouni** [comment]
The  new UI 
image

### Changes 
- Update the page layout to have the upload button and search at the same level 
- Update the filters chips button to take full space available 
image
- Make the metrcis card smaller

**Pull request merged**
