### PR TITLE
Feature: Update footer design

### LINKED ISSUE #224: Refactor portal footer design
See `footer_link` variable in the Configuration file [[Outline](https://doc.jonquetlab.lirmm.fr/doc/ui-dev-environment-GowAei6apP)](https://doc.jonquetlab.lirmm.fr/doc/ui-dev-environment-GowAei6apP)
        

### Requirements 

Remove the  “is currently being developed…” textMake it stick always to the bottom of the screen
- Make as  EcoPortal for the terms, privacy, and Cite Us

Image

            
- Social

Image

### PR DESCRIPTION
**Pull request by Bilelkihal**
### Problem
- The existing footer has bad styling.
- It needs some changes in its elements.
- It doesn't support multilingualism.

### Solution
- I updated the design of the footer.
- I edited some elements and added others.
- I made the footer supports multilingualism.

> $FOOTER_LINKS variable is in the comments below.

### Screenshots
**Before**
image

**After**
Footer

### CODE REVIEW

**Comment by Bilelkihal** [comment]
**$FOOTER_LINKS variable:**

```
$FOOTER_LINKS = {
      en: {
        social: [
          {logo: "social/people.svg", link: "https://github.com/orgs/agroportal/people"},
          {logo: "social/github.svg", link: "https://github.com/agroportal"},
          {logo: "social/twitter.svg", link: "https://twitter.com/lagroportal"},
        ],
        links: [
          {title: "Products", items: [
            {title: "OntoPortal", link: "https://ontoportal.org/"},
            {title: "Release Notes", link: "https://doc.jonquetlab.lirmm.fr/share/e6158eda-c109-4385-852c-51a42de9a412/doc/release-notes-btKjZk5tU2"},
            {title: "API", link: "https://data.agroportal.lirmm.fr/"},
            {title: "SPARQL", link: "https://sparql.agroportal.lirmm.fr/test/"}
            ]},
          {title: "Support", items: [
            {title: "Contact Us", link: "https://agroportal.lirmm.fr/feedback"},
            {title: "NCBO Wiki", link: "https://www.bioontology.org/wiki/"},
            {title: "OntoPortal documentation", link: "https://ontoportal.github.io/documentation/"}
            ]},
          {title: "Disclaimers & Agreements", items: [
            {title: "Terms & Conditions", link: ""},
            {title: "Privacy Policy", link: ""},
            {title: "Cite Us", link: ""},
            {title: "Acknowledgments", link: ""}
            ]},
          {title: "About", items: [
            {title: "About Us", link: "https://github.com/agroportal/project-management"},
            {title: "D2KAB project", link: "https://d2kab.mystrikingly.com/"},
            {title: "Team", link: "https://github.com/orgs/agroportal/people"}
            ]}
        ]
      },
      fr:{
        social: [
          {logo: "social/people.svg", link: "https://github.com/orgs/agroportal/people"},
          {logo: "social/github.svg", link: "https://github.com/agroportal"},
          {logo: "social/twitter.svg", link: "https://twitter.com/lagroportal"},
        ],
        links: [
          {title: "Products", items: [
            {title: "OntoPortal", link: "https://ontoportal.org/"},
            {title: "Release Notes", link: "https://doc.jonquetlab.lirmm.fr/share/e6158eda-c109-4385-852c-51a42de9a412/doc/release-notes-btKjZk5tU2"},
            {title: "API", link: "https://data.agroportal.lirmm.fr/"},
            {title: "SPARQL", link: "https://sparql.agroportal.lirmm.fr/test/"}
            ]},
          {title: "Support", items: [
            {title: "Contact Us", link: "https://agroportal.lirmm.fr/feedback"},
            {title: "NCBO Wiki", link: "https://www.bioontology.org/wiki/"},
            {title: "OntoPortal documentation", link: "https://ontoportal.github.io/documentation/"}
            ]},
          {title: "Disclaimers & Agreements", items: [
            {title: "Terms & Conditions", link: ""},
            {title: "Privacy Policy", link: ""},
            {title: "Cite Us", link: "https://agroportal.lirmm.fr/about"},
            {title: "Acknowledgments", link: "https://agroportal.lirmm.fr/about"}
            ]},
          {title: "About", items: [
            {title: "About Us", link: "https://github.com/agroportal/project-management"},
            {title: "D2KAB project", link: "https://d2kab.mystrikingly.com/"},
            {title: "Team", link: "https://github.com/orgs/agroportal/people"}
            ]}
        ]
      }
    }
```

**Review by syphax-bouazzouni — CHANGES_REQUESTED** [review]
Hi, 
Good work @Bilelkihal 

I approve the code and the design 

I Will give you a remark about the internationalization (also related to  https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/228#issuecomment-1503529338 and @haddadzineddine ).

Everything related to internationalization must be done and centralized in the local's files (e.g` en.yml `and `fr.yml`). Either way, it will be hard to update or extend.

So in summary the footer links variables, need to be like this: 
```ruby 
$FOOTER_LINKS = {
        social: [
          {logo: "social/people.svg", link: "https://github.com/orgs/agroportal/people"},
          {logo: "social/github.svg", link: "https://github.com/agroportal"},
          {logo: "social/twitter.svg", link: "https://twitter.com/lagroportal"},
        ],
        sections: {
          products: {
            ontoportal: "https://ontoportal.org/",
            release_notes: "https://doc.jonquetlab.lirmm.fr/share/e6158eda-c109-4385-852c-51a42de9a412/doc/release-notes-btKjZk5tU2",
            api: "https://data.agroportal.lirmm.fr/",
            sparql: "https://sparql.agroportal.lirmm.fr/test/"
          },
          support: {
            contact_us: "https://agroportal.lirmm.fr/feedback",
            wiki: "https://www.bioontology.org/wiki/",
            documentation: "https://ontoportal.github.io/documentation/"
            },
          agreements: {
            terms: "",
            privacy_policy: "",
            cite_us: "",
            acknowledgments: ""
          },
          about: {
            about_us: "https://github.com/agroportal/project-management",
            projects: "https://d2kab.mystrikingly.com/"},
            team: "https://github.com/orgs/agroportal/people"}
          }
      },
  
    }
  }
}
```

**Comment by Bilelkihal** [comment]
Hi @syphax-bouazzouni,
thank you for the remark.
Done ✅

**Comment by haddadzineddine** [comment]
I have included the appropriate translation for the footer.

see : https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/228/commits/d460c089a6a7fb0821ae2d40ddc848a7a12795c1

**Comment by syphax-bouazzouni** [comment]
Added 

- Add footer `en` translation local file(https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/234/commits/9b6768469fa7fc30178302f6ffdc66d756aaf778)
- Refactor $FOOTER_LINKS loop to use key, value, and not only the keys (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/234/commits/926bbc1275b15261c48d0e3552a807a5d24c9934)
- Fix issue where the footer shift up from the bottom if the page is small (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/234/commits/71083c7643ed96c855c041f9cf46beafb00e96a0)

**Review by syphax-bouazzouni — APPROVED** [review]

**Comment by syphax-bouazzouni** [comment]
The new configration of the footer 
```ruby
$FOOTER_LINKS = {
  social: [
    { logo: "social/people.svg", link: "https://github.com/orgs/agroportal/people" },
    { logo: "social/github.svg", link: "https://github.com/agroportal" },
    { logo: "social/twitter.svg", link: "https://twitter.com/lagroportal" },
  ],
  sections: {
    products: {
      ontoportal: "https://ontoportal.org/",
      release_notes: "https://doc.jonquetlab.lirmm.fr/share/e6158eda-c109-4385-852c-51a42de9a412/doc/release-notes-btKjZk5tU2",
      api: "https://data.agroportal.lirmm.fr/",
      sparql: "https://sparql.agroportal.lirmm.fr/test/"
    },
    support: {
      contact_us: "https://agroportal.lirmm.fr/feedback",
      wiki: "https://www.bioontology.org/wiki/",
      documentation: "https://ontoportal.github.io/documentation/"
    },
    agreements: {
      terms: "",
      privacy_policy: "",
      cite_us: "",
      acknowledgments: ""
    },
    about: {
      about_us: "https://github.com/agroportal/project-management",
      projects: "https://d2kab.mystrikingly.com/",
      team: "https://github.com/orgs/agroportal/people"
    }
  }
}
```

**Pull request merged**
