### PR TITLE
UI improvement

### PR DESCRIPTION
**Pull request by rasmi-aw**
I fixed the misplaced footer in some pages, and added teams page that you can edit from config files only

### CODE REVIEW

**Comment by syphax-bouazzouni** [comment]
Hi @rasmi-aw, thank you for your contribution.

But there are some points to adjust:

1. Your pull requests need to be done now in the ontoportal organization (here https://github.com/ontoportal/ontoportal_web_ui)
2. Your pull requests need to be smaller (47 commits are a lot in only one PR), try to divide them into smaller ones (one for the footer fix and another one for the team page)
3. In your pull request, there are codes related only to the industry portal that you need to remove (e.g  [enit-logo](https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/108/files#diff-725ab53679183242ff96fbd0918e35501733350baecd31ce9af101d70cebc489), ...)


And well done for your merging with our last version of our code (and getting rails 7)

**Comment by rasmi-aw** [comment]
Thanks a lot, i will do that

**Comment by jonquet** [comment]
Can you illustrate the features with a few screenshots ?

**Comment by syphax-bouazzouni** [comment]
Closed because, too much file  changed

**Pull request closed without merging**
