### PR TITLE
Fix: update select_language_label  helper to select f no english found any language remaining over the not tagged

### PR DESCRIPTION
**Pull request by syphax-bouazzouni**
This fixes PR resolve https://github.com/agroportal/project-management/issues/515#issuecomment-2444655766, by selecting any language found over the not tagged ("@none") label in the all languages mode. 
### Before 
image

### After 
image

### CODE REVIEW

**Review by Bilelkihal — APPROVED** [review]

**Comment by Bilelkihal** [comment]
The code is ok for me, 
The idea here is that this works when all languages is selected, and if we're in english for example then we keep showing the fake labels,
wouldn't it be better if we show labels in different languages rather than the fake label that has no information given about the concept (we show the prefix of the language anyway in the tooltip so I think that this will not be confusing for the user)?

what do you think @jonquet @syphax-bouazzouni

**Comment by syphax-bouazzouni** [comment]
> The code is ok for me, The idea here is that this works when all languages is selected, and if we're in english for example then we keep showing the fake labels, wouldn't it be better if we show labels in different languages rather than the fake label that has no information given about the concept (we show the prefix of the language anyway in the tooltip so I think that this will not be confusing for the user)?
> 
> what do you think @jonquet @syphax-bouazzouni

The information the fake ID gives is that there is no label in the selected language. If he wants to see the label in another language he will need to use the selector and choose.

**Comment by Bilelkihal** [comment]
> > The code is ok for me, The idea here is that this works when all languages is selected, and if we're in english for example then we keep showing the fake labels, wouldn't it be better if we show labels in different languages rather than the fake label that has no information given about the concept (we show the prefix of the language anyway in the tooltip so I think that this will not be confusing for the user)?
> > what do you think @jonquet @syphax-bouazzouni
> 
> The information the fake ID gives is that there is no label in the selected language. If he wants to see the label in another language he will need to use the selector and choose.

Let's say I'm a user from the US with my default language EN, I want to see the concepts of MDRFRE ontology, and all I see is some random numbers, I don't know about this story of languages and the ontology is not browsable since all the elements of the tree are number. But seeing them in French or Portuguese will at least give me an idea about what I'm I looking to. what do you think?

**Comment by jonquet** [comment]
Hello. I understand the discussions. Originally (during implementation meetings with Zineddine) we decided that if someone would select a specific language we shall only display in the hierarchy things (if we have) in this language. And if "All languages" is selected then we mix. 
S I would stick with the current implementation for now.

**Pull request merged**
