### PR TITLE
Feature: Add icons in footer page

### PR DESCRIPTION
**Pull request by SirineMhedhbi**
## Context
 Add icons in footer page 
 See here :  https://github.com/ontoportal-lirmm/ontoportal-configs/pull/2
                    https://github.com/ontoportal-lirmm/ontoportal-configs/pull/3
## Changes

- [x] Add email icon .
- [x] Add sparql icon .
- [x] Add api icon .

image

### CODE REVIEW

**Comment by syphax-bouazzouni** [comment]
We updated the icons, here are the new paths:
```ruby 
social: [
    { logo: "social/people.svg", link: "https://github.com/orgs/agroportal/people" },
    { logo: "social/github.svg", link: "https://github.com/agroportal" },
    { logo: "social/twitter.svg", link: "https://twitter.com/lagroportal" },
    { logo: "json.svg", link: $REST_URL },
    { logo: "summary/sparql.svg", link: "#{$SPARQL_URL}/test/"},
    { logo: "social/email.svg", link: $ANNOUNCE_LIST },
  ],
```

**Comment by syphax-bouazzouni** [comment]
Can you add a screenshot of this @SirineMhedhbi.
And add the link to the correspondent PR in the configs repository.
Thanks

**Comment by SirineMhedhbi** [comment]
@done

**Review by syphax-bouazzouni — APPROVED** [review]
Seems really goood

**Pull request merged**
